# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "frogger"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richie Khoo"]
  s.date = "2012-03-17"
  s.description = "Navigating noise in your log files can be like trying to cross a busy road and avoid the cars. Frogger makes your log files more fun by adding some good ol' 8 bit color and a bit of formatting."
  s.email = "evolve2k@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "HISTORY",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "features/enhanced_logger.feature",
    "features/examples_support.feature",
    "features/rspec_examples_support.feature",
    "features/step_definitions/enhanced_logging_steps.rb",
    "features/step_definitions/scenario_outline_steps.rb",
    "features/support/env.rb",
    "frogger.gemspec",
    "lib/frogger.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/evolve2k/frogger"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Frogger makes logs easier to navigate."
  s.test_files = [
    "spec/frogger/cucumber/frog_spec.rb",
    "spec/frogger/rspec/frog_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colored>, [">= 1.2"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.10.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["= 2.6.0"])
      s.add_development_dependency(%q<guard>, ["= 1.0.1"])
      s.add_development_dependency(%q<guard-cucumber>, ["= 0.7.5"])
      s.add_development_dependency(%q<guard-rspec>, ["= 0.6.0"])
    else
      s.add_dependency(%q<colored>, [">= 1.2"])
      s.add_dependency(%q<cucumber>, [">= 0.10.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["= 2.6.0"])
      s.add_dependency(%q<guard>, ["= 1.0.1"])
      s.add_dependency(%q<guard-cucumber>, ["= 0.7.5"])
      s.add_dependency(%q<guard-rspec>, ["= 0.6.0"])
    end
  else
    s.add_dependency(%q<colored>, [">= 1.2"])
    s.add_dependency(%q<cucumber>, [">= 0.10.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["= 2.6.0"])
    s.add_dependency(%q<guard>, ["= 1.0.1"])
    s.add_dependency(%q<guard-cucumber>, ["= 0.7.5"])
    s.add_dependency(%q<guard-rspec>, ["= 0.6.0"])
  end
end

